name: RDP (Optimized)

on:
  workflow_dispatch:

jobs:
  rdp-session:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP and Configure Firewall
        run: |
          # Enable Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name "fDenyTSConnections" -Value 0 -Force

          # Disable NLA (optional, allows easier connection)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name "UserAuthentication" -Value 0 -Force

          # Open RDP port
          netsh advfirewall firewall add rule name="RDP Access" dir=in action=allow protocol=TCP localport=3389

      - name: Create RDP User
        run: |
          $pw = [System.Web.Security.Membership]::GeneratePassword(14,3)
          $sec = ConvertTo-SecureString $pw -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $sec -AccountNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          echo "RDP_USER=RDP" >> $env:GITHUB_ENV
          echo "RDP_PASS=$pw" >> $env:GITHUB_ENV

      - name: Install and Start Tailscale
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
          $file = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $url -OutFile $file
          Start-Process msiexec.exe -ArgumentList "/i `"$file`" /quiet /norestart" -Wait
          Remove-Item $file -Force

          # Connect to your Tailscale network
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} `
            --hostname=gh-runner-$env:GITHUB_RUN_ID

          # Capture IP
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Connection Info
        run: |
          Write-Host "`n=== RDP INFO ==="
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          Write-Host "User: $env:RDP_USER"
          Write-Host "Password: $env:RDP_PASS"
          Write-Host "================"
          Write-Host "Connect via Tailscale from your local client using the above credentials."

      - name: Keep RDP Session Active
        run: |
          Write-Host "RDP session active..."
          while ($true) {
            Start-Sleep -Seconds 300
          }
